name: granity
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  characters: ^1.3.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_date_range_picker: ^0.1.1
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  normalize: ^0.9.1
  provider: ^6.1.2
  table_calendar: ^3.1.2
  uuid: ^4.4.2
  firebase_storage: ^12.1.1
  image_picker: ^1.1.2
  location: ^7.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.7.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.3
  flutter_cache_manager: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
